# Local development configuration
# This file overrides production settings for local development
# Run with: docker compose -f docker-compose.yml -f docker-compose.local.yml up -d

volumes:
  # Local volumes (no external dependencies)
  fluently_pgdata_local:
  fluently_grafana_data_local: 
  fluently_prometheus_data_local:
  fluently_model_cache_local:

services:
  # Speed up ML API startup by using smaller model cache
  ml-api:
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - MODEL_CACHE_SIZE=1GB  # Smaller cache for local development
    volumes:
      # Use local model cache
      - fluently_model_cache_local:/app/.cache/huggingface
      # Map logs to local directory for easier access
      - ./analysis/distractor_api/logs:/app/logs

  # Use local volumes and different port to avoid conflicts
  postgres:
    ports:
      - "5433:5432"  # Use port 5433 to avoid conflicts with local PostgreSQL  
    volumes:
      - fluently_pgdata_local:/var/lib/postgresql/data/pgdata
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Override monitoring services to use local volumes
  grafana:
    volumes:
      - fluently_grafana_data_local:/var/lib/grafana

  prometheus:
    volumes:
      - fluently_prometheus_data_local:/prometheus


