basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: Woolfer0097@yandex.ru
    name: Danila Kochegarov
    url: http://fluently.com
  description: Backend API for Fluently Telegram bot
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://fluently.com/terms/
  title: Fluently API
  version: "1.0"
paths: {}
swagger: "2.0"
